# Numpy 1D en Python

Después de completar esta práctica serás capaz de:

*   Usar la librería `numpy`
*   Realizar operaciones con `numpy`


In [1]:
#Busca en internet como importar numpy
import numpy as np

### Creamos una Lista Python de la siguiente manera:


In [3]:
# Creamos una lista python

a = ["0", 1, "two", "3", 4]
a

['0', 1, 'two', '3', 4]

Podemos acceder a los datos a través del índice:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneList.png" width="660" />


Podemos acceder a cada elemento usando corchetes de la siguiente manera:


In [4]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


<hr>


<h2 id="numpy">¿Qué es Numpy?</h2>


NumPy es una biblioteca de Python que se utiliza para trabajar con matrices, álgebra lineal, transformaciones de Fourier y matrices. Un array numpy es similar a una lista. NumPy significa Numerical Python y es un proyecto de código abierto. El objeto array en NumPy se llama **ndarray**, proporciona muchas funciones de apoyo que hacen que trabajar con ndarray sea muy fácil.

Los arrays se utilizan con mucha frecuencia en la ciencia de datos, donde la velocidad y los recursos son muy importantes.

NumPy generalmente se importa con el alias np.

Por lo general, tiene un tamaño fijo y cada elemento es del mismo tipo. Podemos convertir una lista en un array numpy importando primero `numpy`:


In [5]:
# importamos la librería numpy

import numpy as np 

Después convertimos la lista de la siguiente manera:


In [6]:
# Creamos un array numpy

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

Cada elemento es del mismo tipo, en este caso enteros:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500" />


Al igual que con las listas, podemos acceder a cada elemento mediante corchetes:


In [7]:
# Imprimimos cada elemento

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


### Comprobando la Versión de NumPy

La versión se almacena en el atributo **versión**.


In [8]:
print(np.__version__)

1.22.4


<h3 id="type">Tipo</h3>


Si comprobamos el tipo del array obtenemos <b>numpy.ndarray</b>:


In [9]:
# Comprobamos el tipo del array

type(a)

numpy.ndarray

Como los array numpy contienen datos del mismo tipo, podemos usar el atributo "dtype" para obtener el tipo de datos de los elementos del array. En este caso, es un entero de 64 bits:


In [10]:
# Comprobamos el tipo de valores almacenados en el array numpy

a.dtype

dtype('int64')

### Inténtalo tú mismo

Comprueba el tipo de array y valor para la matriz dada **b**


In [16]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])
# Escriba aquí su solución
type(b)

numpy.ndarray

<h3 id="val">Asignar un valor</h3>


Podemos cambiar el valor del array. Observa el array <code>c</code>:


In [33]:
# Creamos un array numpy

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

Podemos cambiar el primer elemento del array a 100 de la siguiente manera:


In [18]:
# Asignamos 100 al primer elemento

c[0] = 100
c

array([100,   1,   2,   3,   4])

Podemos cambiar el quinto elemento del array a 0 de la siguiente manera:


In [19]:
# Asignamos 0 al 5º elemento

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Inténtalo tú mismo

Asigna el valor 20 para el segundo elemento en el array dada.


In [31]:
a = np.array([10, 2, 30, 40,50])
# Escriba aquí su solución
a[1] = 20
a

array([10, 20, 30, 40, 50])

<h3 id="slice">Slicing (Cortar)</h3>


Al igual que las listas, podemos dividir el array numpy. Slicing (Cortar) en python significa tomar los elementos de un índice dado a otro índice dado.

Cortamos de esta forma: \[start:end].

Podemos seleccionar los elementos del 1 al 3 y asignarlos a un nuevo array numpy <code>d</code> de la siguiente manera:


In [21]:
# Cortamos el array numpy

d = c[1:4]
d

array([1, 2, 3])

Podemos asignar los índices correspondientes a los nuevos valores de la siguiente manera:


In [34]:
# Establecemos el cuarto elemento y el quinto elemento en 300 y 400
print(c)
c[3:5] = 1300, 1400
print(c)

[20  1  2  3  4]
[  20    1    2 1300 1400]


También podemos definir los pasos en el corte, así: \[start\:end:step].


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


Si no damos el start se considera 0


In [36]:
print(arr[:4])

[1 2 3 4]


In [41]:
print(arr[:3])

[1 2 3]


Si no damos el end, se considera hasta la longitud del array.


In [42]:
print(arr[4:])

[5 6 7]


Si no damos el step se considera 1


In [26]:
print(arr[1:5:])

[2 3 4 5]


### Inténtalo tú mismo

Imprime los elementos pares en el array dado.


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Escriba aquí su solución
print(arr[arr% 2 == 0])

[2 4 6 8]


<h3 id="list">Asignar Valor con Listas</h3>


De manera similar, podemos usar una lista para seleccionar más de un índice específico.
La lista `select` contiene varios valores:


In [52]:
# Creamos los índices de la lista

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

Podemos usar la lista como argumento entre paréntesis. El resultado son los elementos correspondientes a los índices concretos:


In [55]:
# Usamos la lista para seleccionar elementos
print(c)
d = c[select]
print(d)

[  20    1    2 1300 1400]
[  20    2 1300 1400]


Podemos asignar a los elementos especificados un nuevo valor. Por ejemplo, podemos asignar los valores a 100 000 de la siguiente manera:


In [58]:
# Asignamos a los elementos especificados un nuevo valor
c[select] = 100000
print(c)

[100000      1 100000 100000 100000]


<h3 id="other">Otros Atributos</h3>


Vamos a revisar algunos atributos básicas de los arrays usando el array <code>a</code>:


In [59]:
# Creamos un array numpy

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

El atributo <code>size</code> es el número de elementos en el array:


In [60]:
# Obtenemos el tamaño del array numpy

a.size

5

Los siguientes dos atributos tendrán más sentido cuando lleguemos a dimensiones más altas, pero repasémoslos. El atributo <code>ndim</code> representa el número de dimensiones del array o el rango del array. En este caso, uno:


In [61]:
# Obtenemos el número de dimensiones del array numpy

a.ndim

1

El atributo <code>shape</code> es una tupla de enteros que indica el tamaño del array en cada dimensión:


In [62]:
# Obtenemos la forma o el tamaño del array numpy

a.shape

(5,)

### Inténtalo tú mismo

Descubre el tamaño, la dimensión y la forma del array dado **b**


In [66]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Escriba aquí su solución
#tamaño
b.size

(7,)

In [68]:
#dimension
b.ndim

1

In [69]:
#forma 
b.shape

(7,)

### Funciones Estadísticas de Numpy


In [70]:
# Creamos un array numpy

a = np.array([1, -1, 1, -1])

In [71]:
# Obtenemos la media del array numpy

mean = a.mean()
mean

0.0

In [72]:
# Obtenemos la desviación estándar del array numpy

standard_deviation=a.std()
standard_deviation

1.0

In [73]:
# Creamos un array numpy

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [74]:
# Obtenemos el valor más grande en el array numpy

max_b = b.max()
max_b

5

In [75]:
# Obtenemos el valor más pequeño en el array numpy

min_b = b.min()
min_b

-1

### Inténtalo tú mismo

Descubre la suma del valor máximo y mínimo en el array numpy dado.


<hr>


In [78]:
c = np.array([-10, 201, 43, 94, 502])

# Escriba aquí su solución
#suma del valor
sum = c.sum()
sum

830

<h2 id="op">Operaciones con Array Numpy</h2>

Podríamos usar operadores aritméticos directamente entre arrays NumPy


<h3 id="add">Suma de Arrays</h3>


Observamos el array numpy <code>u</code>:


In [ ]:
u = np.array([1, 0])
u

Observamos el array numpy <code>v</code>:


In [ ]:
v = np.array([0, 1])
v

Podemos sumar los dos arrays y asignarlas a z:


In [ ]:
# Suma de Arrays Numpy

z = np.add(u, v)
z

La operación es equivalente a la suma de vectores:


In [ ]:
# Trazando Funciones


import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

def Plotvec1(u, z, v):
    
    ax = plt.axes() # generamos los ejes de la ventana completa
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Añadimos una flecha a los ejes U con un ancho de punta de flecha de 0,05, color rojo y una longitud de punta de flecha de 0,1
    plt.text(*(u + 0.1), 'u')#Añadimos el texto u a los Ejes
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Añadimos una flecha a los ejes V con un ancho de punta de flecha de 0,05, color azul y una longitud de punta de flecha de 0,1
    plt.text(*(v + 0.1), 'v')#Añadimos el texto v a los Ejes
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)# Añadimos una flecha a los ejes Z con un ancho de punta de flecha de 0,05 y una longitud de punta de flecha de 0,1
    plt.text(*(z + 0.1), 'z')#Añadimos el texto z a los Ejes
    plt.ylim(-2, 2)#Establecemos el ylim en bottom(-2), top(2)
    plt.xlim(-2, 2)#Establecemos el xlim en left(-2), right(2)

  


In [ ]:
# Trazamos arrays numpy

Plotvec1(u, z, v)

### Inténtalo tú mismo

Realiza la suma de los array numpy dados arr1 y arr2:


In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Escriba aquí su solución

### Resta de Arrays


Observamos el array numpy a:


In [ ]:
a = np.array([10, 20, 30])
a

Observamos el array numpy b:


In [ ]:
b = np.array([5, 10, 15])
b

Podemos restar los dos arrays y asignarlos a c:


In [ ]:
c = np.subtract(a, b)

print(c)

### Inténtalo tú mismo

Realiza la resta de los array numpy dados arr1 y arr2:


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Escriba aquí su solución


<h3 id="multi">Multiplicación de Arrays</h3>


Observamos el array numpy vectorial <code>y</code>:


In [ ]:
# Creamos un array numpy

x = np.array([1, 2])
x

In [ ]:
# Creamos un array numpy

y = np.array([2, 1])
y

Podemos multiplicar cada elemento de la matriz por 2:


In [ ]:
# Multiplicación de Arrays Numpy

z = np.multiply(x, y)
z

Esto es equivalente a multiplicar un vector por un scalar:


### Inténtalo tú mismo

Realiza la multiplicación de los arrays numpy dados arr1 y arr2:


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

# Escriba aquí su solución


### División de Arrays


Observamos el array numpy vectorial a:


In [ ]:
a = np.array([10, 20, 30])
a

Observamos el array numpy vectorial b:


In [ ]:
b = np.array([2, 10, 5])
b

Podemos dividir los dos arrays y asignarlos a c:


In [ ]:
c = np.divide(a, b)
c

### Inténtalo tú mismo

Realiza la división de los arrays numpy dados arr1 y arr2:


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

# Escriba aquí su solución

<h3 id="dot">Producto Escalar</h3>


El producto escalar de los dos array numpy <code>u</code> y <code>v</code> viene dado por:


In [ ]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [ ]:
# Calculamos el producto escalar

np.dot(X, Y)

In [ ]:
#Elementos de X
print(X[0])
print(X[1])

In [ ]:
#Elementos de Y
print(Y[0])
print(Y[1])

Estamos realizando el producto escalar que se muestra a continuación


<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/dot1.png"/>


### Inténtalo tú mismo

Realiza el producto escalar de los array numpy dados ar1 y ar2:


In [ ]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

# Escriba aquí su solución


<h3 id="cons">Añadir una Constante a un Array Numpy</h3>


Observamos el siguiente array:


In [ ]:
# Creamos una constante en un array numpy

u = np.array([1, 2, 3, -1]) 
u

Añadimos la constante 1 a cada elemento del array:


In [ ]:
# Añadimos la constante al array

u + 1

El proceso está resumnido en la siguiente animación:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneAdd.gif" width="500" />


### Inténtalo tú mismo

Añade la Constante 5 al array numpy dado ar:


In [ ]:
arr = np.array([1, 2, 3, -1]) 

# Escriba aquí su solución


<hr>


<h2 id="math">Funciones Matemáticas</h2>


Podemos acceder al valor de <code>pi</code> en numpy de la siguiente manera:


In [ ]:
# El valor de pi

np.pi

Podemos crear la siguiente matriz numpy en Radianes:


In [ ]:
# Creamos el array numpy en radianes

x = np.array([0, np.pi/2 , np.pi])

Podemos aplicar la función <code>sin</code> al array <code>x</code> y asignar los valores al array <code>y</code>; esto aplica la función seno a cada elemento del array:


In [ ]:
# Calculamos el seno de cada elemento

y = np.sin(x)
y

<hr>


<h2 id="lin">Linspace</h2>


Una función útil para trazar funciones matemáticas es <code>linspace</code>. Linspace devuelve números espaciados uniformemente en un intervalo específico.

**numpy.linspace(start, stop, num = valor entero)**

start  :  principio del rango del intervalo

stop   :  final del rango del intervalo

num    :  Número de muestras a generar.


In [ ]:
# Construimos un array numpy de [-2, 2] y 5 elementos

np.linspace(-2, 2, num=5)

Si cambiamos el parámetro <code>num</code> a 9, obtenemos 9 números espaciados uniformemente en el intervalo de -2 a 2:


In [ ]:
# Construimos un array numpy de [-2, 2] y 9 elementos

np.linspace(-2, 2, num=9)

Podemos usar la función <code>linspace</code> para generar 100 muestras espaciadas uniformemente desde el intervalo 0 a 2π:


In [ ]:
# Construimos un array numpy de [0, 2π] y 100 elementos

x = np.linspace(0, 2*np.pi, num=100)

Podemos aplicar la función seno a cada elemento del array <code>x</code> y asignarla al array <code>y</code>:


In [ ]:
# Calculamos el seno de la lista x

y = np.sin(x)

In [ ]:
# Trazamos el resultado

plt.plot(x, y)

### Inténtalo tú mismo

Haz un array numpy de \[5, 4] y 6 elementos


In [ ]:
# Escriba aquí su solución


<hr>


### Iterando Arrays 1-D

Iterar significa pasar por los elementos uno por uno.

Si iteramos en un array 1-D, pasará por cada elemento uno por uno.


Si ejecutamos el array numpy, obtenemos el formato de un array


In [ ]:
arr1 = np.array([1, 2, 3])
print(arr1)

Pero si queremos obtener la forma de la lista, podemos usar un bucle for:


In [ ]:
for x in arr1:
  print(x)

<h2 id="quiz">Cuestionario sobre Array Numpy 1D</h2>


Implementa la siguiente resta vectorial en numpy: u-v


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar

u = np.array([1, 0])
v = np.array([0, 1])

<hr>


Multiplica el array numpy z por -2:


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar

z = np.array([2, 4])

<hr>


Observa las listas <code>\[1, 2, 3, 4, 5]</code> y <code>\[1, 0, 1, 0, 1]</code>. Convierte ambas listas en arrays numpy y luego multiplícalas:


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


<hr>


In [ ]:
# Importamos las librerías

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

def Plotvec2(a,b):
    ax = plt.axes()# generamos los ejes de la ventana completa
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Añadimos una flecha a los ejes a con un ancho de punta de flecha de 0,05, color rojo y una longitud de punta de flecha de 0,1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Añadimos una flecha a los ejes b con un ancho de punta de flecha de 0,05, color azul y una longitud de punta de flecha de 0,1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#Establecemos el ylim en bottom(-2), top(2)
    plt.xlim(-2, 2)#Establecemos el xlim en left(-2), right(2)
    
    


Convierte las listas <code>\[-1, 1]</code> y <code>\[1, 1]</code> en los arrays numpy <code>a</code> y <code>b</code>. Luego, traza los arrays como vectores usando la función <code>Plotvec2</code> y encuentra su producto escalar:


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


<hr>


Convierte las listas <code>\[1, 0]</code> y <code>\[0, 1]</code> en los arrays numpy <code>a</code> y <code>b</code>. Luego, traza los arrays como vectores usando la función <code>Plotvec2</code> y encuentra su producto escalar:


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


<hr>


Convierte las listas <code>\[1, 1]</code> y <code>\[0, 1]</code> en los arrays numpy <code>a</code> y <code>b</code>. Luego, traza los arrays como vectores usando la función <code>Plotvec2</code> y encuentra su producto escalar:


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


<hr>


¿Por qué el resultado del producto escalar para <code>\[-1, 1]</code> y <code>\[1, 1]</code> y del producto escalar para <code>\[1, 0]</code> y <code>\[0, 1]</code> es cero, pero no es cero para el producto escalar de <code>\[1, 1]</code> y <code>\[0, 1]</code>? <p><i>Pista: Estudia las figuras correspondientes, presta atención a la dirección hacia la que apuntan las flechas.</i></p>


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


Convierte las listas <code>\[1, 2, 3]</code> y <code>\[8, 9, 10]</code> en los arrays numpy <code>arr1</code> y <code>arr2</code>. Luego realiza las operaciones <code>Addition</code> , <code>Subtraction</code> , <code>Multiplication</code> , <code>Division</code> y <code>Dot Operation</code> en <code>arr1</code> y <code>arr2</code>.


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar


Convierte las listas <code>\[1, 2, 3, 4, 5]</code> y <code>\[6, 7, 8, 9, 10]</code> en los arrays numpy <code>arr1</code> y <code>arr2</code>. Después encuentra los números pares e impares de <code>arr1</code> y <code>arr2</code>.


In [ ]:
# Escribe tu código debajo y presiona Shift+Enter para ejecutar

